### ISSUE TITLE
Can't find wsf files in development mode

### ISSUE THREAD

**Issue by rendomnet** [kessler/node-regedit#118]
When I use regedit.

[Input Error: Can not find script file "C:\dev\electron\boilerplate\.erb\dll\vbs\regList.wsf".](url)

**Comment by kessler** [comment]
did you read this: https://github.com/ironSource/node-regedit#a-note-about-electron

**Comment by Otaku-gsf** [comment]
same issue in development mode

> did you read this: https://github.com/ironSource/node-regedit#a-note-about-electron

**Comment by kessler** [comment]
can you provide more context please?

**Comment by Nodepad** [comment]
Try this code:
```
if (process.env.NODE_ENV === 'development') {
  setExternalVBSLocation('./node_modules/regedit/vbs');
} else {
  const vbsDirectory = join(dirname(app.getPath('exe')), 'resources/regedit/vbs');
  setExternalVBSLocation(vbsDirectory);
}
```
