### ISSUE TITLE
Altering HKLM hive values is not working if not administrator

### ISSUE THREAD

**Issue by anaszgh** [kessler/node-regedit#49]
its a known thing that for modifying any key's value under HKLM you need a privileged user (Administrator), when trying to put a value which is under HKLM hive, the change will not be saved on the registry, yet the code will complete the process without any errors indicating that the operation succeeded.

Also note that the test defined in the project's source doesn't check the lack of permission for editing values under HKLM.

**Comment by kessler** [comment]
@anaszgh Thanks for the input! It will be really great if you can submit a PR to correct this, or even some sketch code.
